import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { ProductCard } from "@/components/ProductCard";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { getProductBySlug, getSimilarProducts } from "@/lib/products";
import { getCatalogImage } from "@/lib/product-images";
import { getAmazonAffiliateUrl, getAmazonAsin, isAmazonRetailer } from "@/lib/amazon";

type Props = { params: Promise<{ slug: string }> };

function getBaseUrl(): string {
  const configured = process.env.NEXT_PUBLIC_SITE_URL?.trim();
  const fallback = "https://airfryer1.vercel.app";
  if (!configured) return fallback;
  try {
    const url = new URL(/^https?:\/\//i.test(configured) ? configured : `https://${configured}`);
    return url.origin;
  } catch {
    return fallback;
  }
}

function value(v: unknown) { if(v===null||v===undefined||v==="") return "Not listed in source"; if(typeof v==="boolean") return v?"Yes":"No"; return String(v); }
function formatDimensions(v: unknown) { if(!v||typeof v!=="object") return String(v); const d=v as Record<string,unknown>; const inch=d.width_in!==undefined||d.depth_in!==undefined||d.length_in!==undefined||d.height_in!==undefined; const w=d.width_in ?? d.width ?? d.width_cm; const depth=d.depth_in ?? d.length_in ?? d.depth ?? d.depth_cm ?? d.length_cm; const h=d.height_in ?? d.height ?? d.height_cm; if(w!=null&&depth!=null&&h!=null) return inch ? String(w)+"\" W × "+String(depth)+"\" D × "+String(h)+"\" H" : String(w)+" cm W × "+String(depth)+" cm D × "+String(h)+" cm H"; return String(d.raw ?? JSON.stringify(v)); }
function completeness(p: NonNullable<Awaited<ReturnType<typeof getProductBySlug>>>) { const fields=[p.brand_name,p.model,p.description,p.capacity_quart,p.capacity_liters,p.wattage,p.basket_type,p.basket_count,p.dishwasher_safe,p.digital_controls,p.temperature_min,p.temperature_max,p.dimensions,p.weight,p.identifiers.length]; return Math.round(fields.filter(v=>v!==null&&v!==undefined&&v!=="").length/fields.length*100); }
function bestFor(p: NonNullable<Awaited<ReturnType<typeof getProductBySlug>>>) { if((p.basket_count??0)>1)return "cooking two foods at once"; if(p.capacity_quart&&p.capacity_quart<=5)return "compact everyday cooking"; if(p.capacity_quart&&p.capacity_quart>=8)return "larger batches and family cooking"; return "everyday cooking"; }

export async function generateMetadata({params}:Props):Promise<Metadata>{ const {slug}=await params; const p=await getProductBySlug(slug); if(!p||!p.indexable)return {title:"Product",robots:{index:false,follow:true}}; const image=getCatalogImage(p.slug,p.image_url); const seoTitle=[p.brand_name,p.model].filter(Boolean).join(" ") || p.title; const canonical=`/products/${p.slug}`; const description=p.description??`Verified Amazon air fryer product record for ${p.title}. Compare specifications and open the Amazon product page.`; return {title: seoTitle + " Air Fryer — Specs & Amazon",description,alternates:{canonical},openGraph:{title:seoTitle+" Air Fryer — Specs & Amazon",description,type:"website",url:canonical,images:image?[{url:image,alt:p.title}]:undefined},twitter:{card:"summary_large_image",title:seoTitle+" Air Fryer — Specs & Amazon",description,images:image?[image]:["/twitter-image"]}}; }

export default async function ProductPage({params}:Props){ const {slug}=await params; const p=await getProductBySlug(slug); if(!p)notFound(); const [similar]=await Promise.all([getSimilarProducts(p.id,6)]); const image=getCatalogImage(p.slug,p.image_url); const offers=(p.offers??[]).filter((offer)=>isAmazonRetailer(offer.retailer_slug)); const amazonAsin=getAmazonAsin(p.identifiers); if(!amazonAsin)notFound(); const amazonUrl=getAmazonAffiliateUrl(amazonAsin); const score=completeness(p); const baseUrl=getBaseUrl(); const fields:Array<[string,unknown]>=[["Capacity",p.capacity_quart?`${p.capacity_quart} qt`:null],["Capacity liters",p.capacity_liters?`${p.capacity_liters} L`:null],["Power",p.wattage?`${p.wattage} W`:null],["Basket",p.basket_type],["Basket count",p.basket_count],["Controls",p.digital_controls===null?null:p.digital_controls?"Digital":"Manual"],["Dishwasher safe",p.dishwasher_safe],["Rotisserie",p.rotisserie],["Temperature",p.temperature_min!=null&&p.temperature_max!=null?`${p.temperature_min}–${p.temperature_max} °F`:p.temperature_max!=null?`Up to ${p.temperature_max} °F`:null],["Dimensions",p.dimensions?formatDimensions(p.dimensions):null],["Weight",p.weight?`${p.weight} kg`:null]]; const jsonLd={"@context":"https://schema.org","@type":"Product",name:p.title,description:p.description??undefined,brand:p.brand_name?{"@type":"Brand",name:p.brand_name}:undefined,model:p.model??undefined,image:image?[image]:undefined,sku:p.model??undefined,...(p.identifiers.find(i=>i.identifier_type.toUpperCase()==="UPC")?.identifier_value?{gtin12:p.identifiers.find(i=>i.identifier_type.toUpperCase()==="UPC")?.identifier_value}:{}),...(p.identifiers.find(i=>i.identifier_type.toUpperCase()==="EAN")?.identifier_value?{gtin13:p.identifiers.find(i=>i.identifier_type.toUpperCase()==="EAN")?.identifier_value}:{}),...(offers.some(o=>o.price!=null&&Boolean(o.affiliate_url||o.url))?{offers:offers.filter(o=>o.price!=null&&Boolean(o.affiliate_url||o.url)).map(o=>({"@type":"Offer",price:o.price,priceCurrency:o.currency??"USD",url:o.affiliate_url??o.url,availability:o.availability==="in_stock"?"https://schema.org/InStock":o.availability==="out_of_stock"?"https://schema.org/OutOfStock":undefined}))}: {})}; const breadcrumbLd={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:baseUrl+"/"},{"@type":"ListItem",position:2,name:"Air Fryers",item:baseUrl+"/air-fryers"},{"@type":"ListItem",position:3,name:p.title,item:baseUrl+"/products/"+p.slug}]};
 return <main><SiteHeader/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbLd)}}/><section className="product-hero"><div className="shell"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/air-fryers">Air Fryers</Link>{p.brand_name&&<><span>/</span><span>{p.brand_name}</span></>}<span>/</span><span>{p.model??p.title}</span></nav><div className="product-hero__grid"><div className="product-visual"><span className="eyebrow">PRODUCT IMAGE</span>{image?<div className="product-image"><Image src={image} alt={p.title} width={800} height={800} priority sizes="(max-width: 767px) 100vw, 42vw"/></div>:<div className="product-placeholder"><span>AF</span></div>}</div><div className="product-copy"><span className="eyebrow">{p.brand_name??"BRAND UNVERIFIED"}</span><h1 className="product-title">{p.title}</h1>{p.model&&<p className="product-hero__model">Model: {p.model}</p>}<div className="product-hero__status"><span className="status-pill">Catalog record</span>{p.human_verified&&<span className="status-pill status-pill--verified">Human verified</span>}{p.identifiers.length>0&&<span className="status-pill">{p.identifiers.length} verified ID{p.identifiers.length===1?"":"s"}</span><span className="status-pill status-pill--amazon">Amazon</span>}</div><p>{p.description??"Structured product information from the current catalog record. Missing values are not inferred or generated."}</p><div className="trust-strip"><span><b>{score}%</b> data completeness</span><span><b>Best for</b> {bestFor(p)}</span></div><dl className="quick-specs">{[["Capacity",p.capacity_quart?`${p.capacity_quart} qt`:null],["Basket",p.basket_type],["Power",p.wattage?`${p.wattage} W`:null],["Controls",p.digital_controls===null?null:p.digital_controls?"Digital":"Manual"]].map(([label,v])=>v?<div className="quick-specs__item" key={label}><dt className="quick-specs__label">{label}</dt><dd className="quick-specs__value">{v}</dd></div>:null)}</dl><div className="action-row">
{amazonUrl && <a href={`/go/${encodeURIComponent(p.slug)}`} className="button button--primary" rel="nofollow sponsored">View on Amazon</a>}
<Link href={`/compare?a=${encodeURIComponent(p.slug)}`} className="button">Compare this model</Link>


</div>{amazonUrl&&<p className="affiliate-disclosure">As an Amazon Associate I earn from qualifying purchases.</p>}</div></div></div></section><section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">QUICK VERDICT</span><h2>What to know before choosing</h2></div></div><div className="insight-grid"><div className="insight-card"><b>Best for</b><p>This model appears suited to {bestFor(p)} based only on the catalog fields available.</p></div><div className="insight-card"><b>Verified</b><p>{p.identifiers.length?`${p.identifiers.length} verified product identifier${p.identifiers.length===1?"":"s"} are available.`:"No verified product identifier is attached to this record."}</p></div><div className="insight-card"><b>Missing</b><p>{amazonUrl?"This page links directly to the Amazon product identified by the verified ASIN. Current Amazon price and availability are checked on Amazon.":"No verified Amazon link is available for this record."}</p></div></div></div></section><section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">SPECIFICATIONS</span><h2>Key specifications</h2></div></div><div className="spec-table">{fields.map(([label,v])=><div key={label}><b>{label}</b><span>{value(v)}</span></div>)}</div></div></section>{p.identifiers.length>0&&<section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">IDENTITY</span><h2>Verified identifiers</h2></div></div><div className="identifiers">{p.identifiers.map(i=><span className="identifiers__item" key={`${i.identifier_type}-${i.identifier_value}`}><span>{i.identifier_type}</span>{i.identifier_value}</span>)}</div></div></section>}{offers.length>0&&}{similar.length>0&&<section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">ALTERNATIVES</span><h2>Similar air fryers</h2></div></div><div className="product-grid">{similar.map(i=><ProductCard key={i.slug} product={i}/>)}</div></div></section>}<SiteFooter/></main>; }
